server:
  port: 8080
  servlet:
    context-path: "/api"
  ssl:
    key-store: classpath:zyyyyds.top
    key-store-type: jks
    key-store-password: 0en46uo7oz
    key-alias: zyyyyds.top


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ScheduleMiniProgram?setUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 200MB #设置上传文件大小不得超过200MB
      max-request-size: 210MB #设置一次请求的数据量不得超过200MB
      enabled: true
  web:
    resources:
      static-locations: classpath:/static/

mybatis:
  mapper-locations: classpath:/mapper/*.xml
